name: Build wheels

on:
  push:
    branches: [ develop ]

  # run this workflow manually from the Actions tab
  workflow_dispatch:

# EnergyPlus 23.1.0 commit
env:
  EnergyPlus_Commit: 87ed9199d4

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout pyenergyplus
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: build wheels
      run: |
        pip install wheel
        cd EnergyPlus
        git checkout $EnergyPlus_Commit
        cd ..
        sudo apt-get install ninja-build
        python setup.py bdist_wheel

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist


  build_test_osx:
    runs-on: macos-latest
    env:
      FC: gfortran-11
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout pyenergyplus
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and test
      run: |
        pip install wheel
        cd EnergyPlus
        git checkout $EnergyPlus_Commit
        cd ..
        brew install ninja
        python setup.py bdist_wheel

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist


  build_test_windows:
    runs-on: windows-2019
    env:
      CMAKE_Fortran_COMPILER: "/c/msys64/mingw64/bin/x86_64-w64-mingw32-gfortran.exe"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout pyenergyplus
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and test
      run: |
        pip install wheel
        cd EnergyPlus
        git checkout 87ed9199d4
        cd ..
        python setup.py bdist_wheel

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist
