name: Build wheels

on:
  # push:
  #  branches:
  #    - develop
  #    - wheel
  #  tags:
  #    - "*"

  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag, or SHA for which to run (eg: v22.1.0 or develop)'
        required: true

jobs:
  build_wheel:
    name: Build Python Wheels
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-22.04]  # , macos-13, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout EnergyPlus
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: build wheels
      run: |
        pip install wheel
        python setup.py bdist_wheel

    - uses: actions/upload-artifact@v4
      with:
        name: energyplus-wheel-${{ matrix.os }}
        path: ./dist

    - name: Deploy on Test PyPi
      uses: pypa/gh-action-pypi-publish@v1.10.3
      with:
        repository-url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.TESTPYPIPW }}
        verbose: true
