name: CppCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout EnergyPlus
      uses: actions/checkout@v3

    - name: Install CppCheck
      run: sudo apt-get install cppcheck

    - name: Run CppCheck
      working-directory: ${{runner.workspace}}/EnergyPlus/src
      run: cppcheck --template='[{file}]:{line}:{severity}:{message}' --suppress="uninitvar:*" .
