name: Mac Releases

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_TYPE: Release
  FC: /usr/local/bin/gfortran-9
  MACOSX_DEPLOYMENT_TARGET: 10.15
  SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

jobs:
  mac_release:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: Install System dependencies and LaTeX
      shell: bash
      run: |
        set -x
        echo "Using brew to install mactex and adding it to PATH"
        brew install --cask mactex
        echo "/Library/TeX/texbin" >> $GITHUB_PATH

    - name: Install IFW
      shell: bash
      run: |
        set -x
        out_dir=${{ runner.workspace }}/Qt
        aqt tool mac tools_ifw 4.1 qt.tools.ifw.41 --outputdir="$out_dir"
        echo "$out_dir/Tools/QtInstallerFramework/4.1/bin" >> $GITHUB_PATH

    - name: Create Build Directory
      run: cmake -E make_directory ./build/

    - name: Configure CMake
      working-directory: ./build
      shell: bash
      run: |
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET \
              -DLINK_WITH_PYTHON=ON  -DBUILD_FORTRAN=ON -DBUILD_PACKAGE:BOOL=ON \
              -DDOCUMENTATION_BUILD="BuildWithAll" -DTEX_INTERACTION="batchmode" \
              ../

    - name: Build Package
      working-directory: ./build
      shell: bash
      run: cmake --build . --target package -j 2

    - name: Upload Tarball to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/EnergyPlus-*-x86_64.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

    - name: Upload DMG to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/EnergyPlus-*-x86_64.dmg
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
